### PR TITLE
flake8 fixes

### PR DESCRIPTION
**Pull request by bje-**
This silences some warnings from `flake8`.

### CODE REVIEW

**Comment by jotaigna** [comment]
Thank you for the submission. It is odd that they are not detected in my system even though I have flake8. Any option you put besides `max-line-length`?

**Comment by bje-** [comment]
I do tend to run the bleeding edge:
```
3.7.7 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.6.7 on Linux
```

How does this differ to the versions you have installed?

**Comment by jotaigna** [comment]
3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.15rc1 on Linux

**Comment by bje-** [comment]
Looks like you're a fair way behind :-)

**Comment by jotaigna** [comment]
Yes, and upon update I now see those. Thanks!

**Pull request merged**
